-- liquibase formatted sql

-- changeset vadimgupal:1
CREATE TABLE IF NOT EXISTS tasks
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) NOT NULL,
    description TEXT NOT NULL,
    priority INT NOT NULL DEFAULT 0 CHECK (priority BETWEEN 0 AND 10),
    deadline TIMESTAMPTZ NOT NULL
);
--rollback DROP TABLE IF EXISTS tasks;