-- liquibase formatted sql

-- changeset vadimgupal:0
CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    chat_id BIGINT NOT NULL UNIQUE
);
--rollback DROP TABLE IF EXISTS users;