-- liquibase formatted sql

-- changeset vadimgupal:0
CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL
);
--rollback DROP TABLE IF EXISTS users;