spring:
  application:
    name: Scheduly
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  output:
    ansi:
      enabled: always

logging:
  charset:
    console: UTF-8
    file: UTF-8

app:
  telegram-token: ${TOKEN}
  core-base-url: ${CORE_BASE_URL:http://localhost:8081}

server:
  port: 8080
