spring:
  application:
    name: Scheduly
  data:
    redis:
      host: localhost
      port: 6379
  output:
    ansi:
      enabled: always

logging:
  charset:
    console: UTF-8
    file: UTF-8

app:
  telegram-token: ${TOKEN}

server:
  port: 8080
