app:
  auth-uri: ${AUTH_URI}
  client-id: ${CLIENT_ID}
  redirect-uri: ${REDIRECT_URI}
  token-uri: ${TOKEN_URI}
  client-secret: ${CLIENT_SECRET}
  bot-base-url: ${BOT_BASE_URL:http://localhost:8080}

spring:
  application:
    name: core
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  output:
    ansi:
      enabled: always

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/scrapper}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

server:
  port: ${SERVER_PORT:8081}

logging:
  charset:
    console: UTF-8
    file: UTF-8